// Inherit the parent event
event_inherited();

iron = 1;

name = "Google Earth Satellite";

desc = "This is an example of how a Google Earth satellite could look like. Pretty cool, right? Those machines are responsible for taking those beautiful sights of our planet Earth. Imagery resolution ranges from 15 meters of resolution to 15 centimeters. For much of the Earth, Google Earth uses digital elevation model data collected by NASA's Shuttle Radar Topography Mission. This creates the impression of three-dimensional terrain, even where the imagery is only two-dimensional. The maps generated by Google are copyrighted so be careful how you use them. By contrast, images created with NASA's globe software WorldWind use The Blue Marble, Landsat, or USGS imagery, each of which is in the public domain.";
